##### DECLARATIONS #####
# Variables
variables:
  - group: IronDrawingVersions
  - name: Configuration
    value: 'Release'
  - name: AssemblyVersion
    value: 1.0.0.$(Build.BuildID)
# Build Trigger
trigger:
    branches:
      include:
      - master
# Virtual Machine
pool:
  vmImage: 'windows-latest'
##### STEPS #####
stages:
## Compile
- stage: BuildDrawingLibraries
  displayName: Build IronSoftware.Drawing Libraries
  dependsOn: []
  jobs:
  - template: job_templates/build_drawing_libraries.yml
    parameters:
      publishAssemblies: true
      buildConfiguration: $(Configuration)
## Test Windows
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Windows'
    pool:
      vmImage: 'windows-latest'
## Test Linux
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Linux'
    pool:
      vmImage: 'ubuntu-latest'
## Test MacOs
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'MacOs'
    pool:
      vmImage: 'macOS-latest'
## Push NuGet Package
- stage: DeployDrawingLibraries
  pool:
    vmImage: 'windows-latest'
  displayName: Deploy NuGet Package
  dependsOn:
    - WindowsTests
    - LinuxTests
    - MacOsTests
  jobs:
  - template: job_templates/deploy_drawing_libraries.yml
