pr:
  - master
  - main
  - multiple-framework-croprectangle


pool:
  vmImage: 'windows-latest'

variables:
  - group: IronDrawingVersions
  - name: buildConfiguration
    value: 'Debug'
  - name: AssemblyVersion
    value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingRevisionVersion).$(Build.BuildID)

jobs:
  - job: CheckoutAndRestore
    displayName: Checkout & Restore IronSoftware.Drawing
    steps:
    - checkout: self
      displayName: Checkout IronSoftware.Drawing git repository
      lfs: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '7.x'
        includePreviewVersions: true

    - task: NuGetToolInstaller@1
      displayName: Install NuGet Manager
      inputs:
        versionSpec:
        checkLatest: true

    - task: DotNetCoreCLI@2
      displayName: 'Restore Solution NuGet Packages'
      enabled: true
      continueOnError: true
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.sln'
        verbosityRestore: 'Normal'
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)/IronSoftware.Drawing/nuget.config'

    - task: DotNetCoreCLI@2
      displayName: Build IronPDF Solution
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.sln'
        arguments: '--configuration $(buildConfiguration) --no-restore --verbosity normal'
        versioningScheme: byEnvVar
        versionEnvVar: AssemblyVersion

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests'
        artifact: 'IronDrawingUnitTests'
        publishLocation: 'pipeline'

  - job: BuildAndTestNet50
    displayName: Build & Test .Net50
    dependsOn: [CheckoutAndRestore]
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingUnitTests'
        targetPath: '$(Build.SourcesDirectory)/IronDrawingUnitTests'

    - task: DotNetCoreCLI@2
      displayName: Build Solution
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/IronDrawingUnitTests/IronSoftware.Drawing.Common.Tests.csproj'
        arguments: '--configuration $(buildConfiguration) -f "net50" --no-restore --verbosity normal'

    - task: DotNetCoreCLI@2
      displayName: Execute Unit Tests
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/IronDrawingUnitTests/IronSoftware.Drawing.Common.Tests.csproj'
        arguments: '--configuration "$(buildConfiguration)" -f "net50" --verbosity n --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
        testRunTitle: 'Execute Unit Tests'
      condition: succeededOrFailed()

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      
    - task: PublishTestResults@2
      displayName: 'Publish test result'
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'

  - job: BuildAndTestNet60
    displayName: Build & Test .Net60
    dependsOn: [CheckoutAndRestore]
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingUnitTests'
        targetPath: '$(Build.SourcesDirectory)/IronDrawingUnitTests'

    - task: DotNetCoreCLI@2
      displayName: Execute Unit Tests
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/IronDrawingUnitTests/IronSoftware.Drawing.Common.Tests.csproj'
        arguments: '--configuration "$(buildConfiguration)" -f "net60" --verbosity n --no-build'
        testRunTitle: 'Execute Unit Tests'
      condition: succeededOrFailed()

  - job: BuildAndTestNetCore21
    displayName: Build & Test .Netcore2.1
    dependsOn: [CheckoutAndRestore]
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingUnitTests'
        targetPath: '$(Build.SourcesDirectory)/IronDrawingUnitTests'

    - task: DotNetCoreCLI@2
      displayName: Execute Unit Tests
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/IronDrawingUnitTests/IronSoftware.Drawing.Common.Tests.csproj'
        arguments: '--configuration "$(buildConfiguration)" -f "netcoreapp2.1" --verbosity n --no-build'
        testRunTitle: 'Execute Unit Tests'
      condition: succeededOrFailed()

  - job: BuildAndTestNetCore31
    displayName: Build & Test .Netcore3.1
    dependsOn: [CheckoutAndRestore]
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingUnitTests'
        targetPath: '$(Build.SourcesDirectory)/IronDrawingUnitTests'

    - task: DotNetCoreCLI@2
      displayName: Execute Unit Tests
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/IronDrawingUnitTests/IronSoftware.Drawing.Common.Tests.csproj'
        arguments: '--configuration "$(buildConfiguration)" -f "netcoreapp3.1" --verbosity n --no-build'
        testRunTitle: 'Execute Unit Tests'
      condition: succeededOrFailed()

  - job: BuildAndTestNet70
    displayName: Build & Test .Net70
    dependsOn: [CheckoutAndRestore]
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingUnitTests'
        targetPath: '$(Build.SourcesDirectory)/IronDrawingUnitTests'

    - task: DotNetCoreCLI@2
      displayName: Execute Unit Tests
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)/IronDrawingUnitTests/IronSoftware.Drawing.Common.Tests.csproj'
        arguments: '--configuration "$(buildConfiguration)" -f "net70" --verbosity n --no-build'
        testRunTitle: 'Execute Unit Tests'
      condition: succeededOrFailed()
