##### DECLARATIONS #####
# Variables
parameters:
  - name: UnitTests
    displayName: Unit Tests
    type: boolean
    default: True
  - name: githubRelease
    displayName: GitHub Release
    type: boolean
    default: True
  - name: preRelease
    displayName: Pre-Release
    type: boolean
    default: true
variables:
  - group: IronDrawingVersions
  - name: Configuration
    value: 'Release'
  - name: AssemblyVersion
    value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingRevisionVersion).$(IronDrawingPatch)
  - name: NugetVersion
    ${{ if eq(parameters.preRelease, true) }}:
      value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingPatch)-prerelease
    ${{ if ne(parameters.preRelease, true) }}:
      value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingPatch)
    
# Virtual Machine
pool:
  vmImage: 'windows-latest'
##### STEPS #####
stages:
## Compile
- stage: BuildDrawingLibraries
  displayName: Build IronSoftware.Drawing Libraries
  dependsOn: []
  jobs:
  - template: job_templates/build_drawing_libraries.yml
    parameters:
      publishAssemblies: true
      buildConfiguration: $(Configuration)
## Test Windows
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Windows'
    pool:
      vmImage: 'windows-latest'
    runUnitTests: ${{ parameters.UnitTests }}
## Test Linux
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Linux'
    pool:
      vmImage: 'ubuntu-latest'
    runUnitTests: ${{ parameters.UnitTests }}
## Test MacOs
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'MacOs'
    pool:
      vmImage: 'macOS-latest'
    runUnitTests: ${{ parameters.UnitTests }}
## Push NuGet Package
- stage: DeployDrawingLibraries
  pool:
    vmImage: 'windows-latest'
  displayName: Deploy NuGet Package
  dependsOn:
    - WindowsTests
    - LinuxTests
    - MacOsTests
  jobs:
  - template: job_templates/deploy_drawing_libraries.yml
    parameters:
      NuGetVersion: $(NuGetVersion)
